package com.anczykowski.errormodule;

public enum ErrorType {
    INCONSISTENT_LINE_ENDINGS,
    TOKEN_TOO_LONG,
    UNKNOWN_CHARACTER,
    UNCLOSED_STRING,
    CONSTANT_TOO_BIG,
    MALFORMED_NUMBER,
    UNEXPECTED_TOKEN,
    ALREADY_DECLARED,
    DUPLICATE_LABEL,
    UNSUPPORTED_CHAINING,
    UNMATCHED_ARGUMENTS,
}
